= Teh Wen Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ePiggy

---

== Overview

This portfolio aims to document my contributions to *_ePiggy_*.

*_ePiggy_* Github link: https://github.com/CS2103-AY1819S2-W17-4/main

== Introduction

=== About

*ePiggy* is a desktop application designed to inculcate good spending habits in students
through allowing them to track their finances. It includes everything from tracking expenses, managing budgets
to setting goals. +

It is written in Java. Interactions by users are done through the Command Line Interface (CLI) and it has a Graphical User Interface (GUI) created with JavaFX. +
It can be used on both Windows and Mac.

=== Project Team

*_ePiggy_* was morphed from the link:https://github.com/nus-cs2103-AY1819S2/addressbook-level4[AddressBook - Level 4] application. My team consists of
5 members. I contributed the `budget` feature of *_ePiggy_*, which allows users to add, edit and delete budgets to track their spendings.

== Summary of contributions

=== Major Enhancements

Added the `budget` feature of ePiggy. +

* *What it does:*
The `budget` feature allows users to set a limit on their spendings for a specified time period and provide reminders when they are going to or have exceeded the limit. +

* *Justification:*
It urges users to be more aware of the amount they spend per time period so that they can better manage their expenses and avoid splurging. It is also a good habit we hope to inculcate in users before they enter the
workforce and deal with larger sums of money. +

* *Highlights:*
** This enhancement was built from scratch. It is completely new and hence required the creation of many new objects including `budget`, `period`, `uniqueBudgetList` and a new `budgetPanel` for the UI. This enhancement required the familiarity with
almost all the different areas of the code (`commons`, `logic`, `model`, `ui`).
** For this enhancement, the UI is important as the purpose is to constantly remind users of the remaining amount they can spend. It was challenging to make the UI simple and concise for our target users whilst conveying the crucial information.

=== Minor Enhancements
* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

=== Other Contributions
* *Other contributions*:

** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Standardised and beautified the User Guide
**** Designed and added the header and images across the user guide to suit our target user
**** Standardised the language and formatting of the user guide
*** Standardised and beautified the Developer Guide
**** Designed and added the header
**** Standardised the language and formatting of the user guide
** Community:
*** PRs contributed:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
** Tools:
*** Created the *.jar file for ePiggy
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo
** All code contributed:
**** View the codes I contributed here
_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
