= Wu Yunjun - Project Portfolio for ePiggy
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: ePiggy

---

== About the project

My team and I designed to modify a basic command line interface addressbook4 for our Software Engineering project.
We chose to change some logic and methods in addressbook4 so that it became a useful accounting software calls ePiggy.
The ePiggy aids to inculcate good spending habits in students. At the same time, ePiggy supports budgets, expenses and allowances management.
Student can use it to manage money easily by single and simply commands.

My role was to design and write the codes for the report and auto-complete features. The following sections
illustrate these enhancements in more detail, as well as the relevant sections I have added to the
user and developer guides in relation to these enhancements.

Note the following symbols and formatting used in this document:

[NOTE]


[width="59%",cols="30%,70%",options="header",]
|=======================================================================
|[NOTE] |This symbol indicates important information.
|`report` | A grey highlight (called a mark-up) indicates that this is a command
           that can be inputted into the command line and executed by the
           application.

|`ReportWindow` |Blue text with grey highlight indicates a component, class or object in
                 the architecture of the application.

|=======================================================================

== Summary of contributions

This section shows a summary of my coding, documentation, and other helpful contributions to the
team project.

*Major enhancement*

* I added a `report` command for ePiggy: +
** What it does: The `report` command allows the user to view a report (summary) of expenses, budgets and allowance on specified date, month or year.
** Justification: If user wants to manage his/her money better, the report command enables ePiggy to generate a visualized report of specified date, month or year with different charts. The user can have a better idea of how much he/she spend or how much he/she save in that period of time.
** Highlights: This command works with existing advanced features such as budget and allowance management. The implementations were challenging as it required good understanding of the addressbook4 structure and JavaFX.
** Credits: JavaFX basic feature online tutorials, JavaFX advanced features (charts) tutorials.

* I added auto complete feature for ePiggy +
** What it does: user enters first few letters of the command, and then press ‘Tab’ key on the keyboard. The completed command will show on the text field.
** Justification: In case the user forgot some of the commands, he/she can quickly find the correct command format by press the ‘Tab’ key. If user forgot the parameters of the command, he/she can also use it function fill in the correct parameters of the command.

* *Code contributed*: Please click these links to see a sample of my code:
https://github.com/yunjun199321/main/commits?author=yunjun199321[Code contribution]
https://github.com/yunjun199321/main/commit/fcc384f89b82596b30448aa47c6f4b64151e67c7[Auto Complete function]|
https://github.com/yunjun199321/main/commit/17e48dfc8f152ba857fbe41ac729d03f20c493be[Report command phaser and UI button]|
https://github.com/yunjun199321/main/commit/9cfcc856b16a1da07112742a670aee9a38208103[JavaFX charts]

* *Other contributions*:

** Project management:
*** manage releases version 1.1 to 1.3 on GitHub
** Enhancements to existing features:
*** Updated the ePiggy icon and name
*** Wrote additional tests for existing features to increase coverage
*** Fix some old tests to increase coverage
** Documentation:
*** Made cosmetic improvements to the existing User Guide to make it more reader-friendly
*** Update User Guide and Developer Guide
*** Add user stories
** Community:
*** PRs reviewed
*** Contributed to forum discussions
*** Reported bugs and suggestions for other teams in the class
** Tools:
*** Setup GitHub home-page and issue template
*** Setup Travis CI

== Contributions to the User Guide

We had to update the original addressbook4 User Guide with instructions for the enhancements that
we had added. The following is an excerpt from our ePiggy User Guide, showing the details of report features and auto complete function.

include::../UserGuide.adoc[tag=report]

== Auto complete:
Enter the first few letters of the command or tag, and then press Tab key on the keyboard to auto complete the command.
If the auto complete command is not what you want, delete some letters and press Tab again. Another command will show.

Example: Enter letter 'a' and then press Tab, the `addExpense n/ $/ t/ d/` will show.

include::../UserGuide.adoc[tag=v2.0]

== Contributions to the Developer Guide
The following section shows my additions to the ePiggy Developer Guide for the report and auto complete features.

include::../DeveloperGuide.adoc[tag=report]
